# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0JJTFcKdpJx_8Nz172Udv4TZZ2dLEIl
"""

import streamlit as st

st.sidebar.header("Hiperparámetros de Red")
ecuacion = st.sidebar.text_input("Función de Pérdida:")
lr = st.sidebar.number_input("Tasa de Aprendizaje:")
epochs = st.sidebar.slider("Épocas Máximas:", 100, 10000)
momentum = st.sidebar.slider("Momentum (Inercia):", 0.0, 0.99)

btn_entrenar = st.sidebar.button("Entrenar Modelo")